=== HertRain/Cinema/bin/com/cinema/file/Movie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT MovieList (Movie+)>
<!ELEMENT Movie (Name,Poster,Director,Actors,Type,Price,Schedule)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Poster (#PCDATA)> 
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Actors (Actor+)>
<!ELEMENT Actor (#PCDATA)>
<!ELEMENT Type (#PCDATA)> 
<!ELEMENT Price (#PCDATA)> 
<!ELEMENT Schedule (Item+)>
<!ELEMENT Item (#PCDATA)>

=== HertRain/Cinema/src/com/cinema/file/Movie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MovieList SYSTEM "Movie.dtd">
	<MovieList>
		<Movie>
			<Name>战狼2</Name>
			<Poster>Wolf Warriors Ⅱ</Poster>
			<Director>吴京</Director>
			<Actors>
				<Actor>吴京</Actor>
				<Actor>吴刚</Actor>
				<Actor>卢靖姗</Actor>
			</Actors>
			<Type>Action</Type>
			<Price>51</Price>
			<Schedule>
				<Item>9:00</Item>
				<Item>10:30</Item>
				<Item>13:00</Item>
			</Schedule>
		</Movie>
	</MovieList>
